export const ActionTypes = {
    SHOW_MODELS: "SHOW_MODELS",

    SHOW_RELOAD: "SHOW_RELOAD",

    SET_AUDIOS: "SET_AUDIOS",
    ORDER_BY_AUDIOS: "ORDER_BY_AUDIOS",
    SET_LABELS_AUDIOS: "SET_LABELS_AUDIOS",
    SET_STREAM_AUDIO: "SET_STREAM_AUDIO",
    SET_STREAM_AUDIO_DURATION: "SET_STREAM_AUDIO_DURATION",
};
