# Partir de l'image node:latest
FROM node:18-slim

# Exposer le port 8000 du conteneur
EXPOSE 8000

# Copier le dossier PS8 et tout son contenu vers le conteneur
COPY serveur /app

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances
RUN npm install

# Démarrer l'application
CMD ["npm", "run", "dev"]

