version: '3'
services:
  mongo:
    image: mongo:6.0.6
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root2
      ME_CONFIG_MONGODB_ADMINPASSWORD: example2
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  data:
    driver: local
