FROM tensorflow/tensorflow:2.12.0

EXPOSE 2834

WORKDIR /app

COPY ../backend .

RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash - && \
    apt-get install -y nodejs

WORKDIR /app/CNN

RUN pip3 install --upgrade pip

RUN pip install tensorflow-intel

RUN pip install -r requirements.txt

WORKDIR /app

CMD ["npm", "run", "dev"]

