FROM node:18-slim AS back

EXPOSE 80

WORKDIR /app/back

COPY ../backend .

RUN npm install

# Démarrer l'application
CMD ["npm", "run", "dev"]

FROM python:3.11 AS ml

WORKDIR /app/CNN

COPY ../backend/CNN .

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN echo $PATH

RUN pip install -r requirements.txt

WORKDIR /app

