FROM python:3.11

EXPOSE 80

WORKDIR /app

COPY ../backend .

RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash - && \
    apt-get install -y nodejs


WORKDIR /app/CNN

RUN pip3 install --upgrade pip

RUN pip install tensorflow-intel

RUN pip install -r requirements.txt

WORKDIR /app

# Démarrer l'application
CMD ["npm", "run", "dev"]
#CMD ["python", "LSTM_Classification.py"]
